//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoClientes.Web.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/GestaoClientes.Api.Models")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SituacaoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TipoIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SituacaoID {
            get {
                return this.SituacaoIDField;
            }
            set {
                if ((this.SituacaoIDField.Equals(value) != true)) {
                    this.SituacaoIDField = value;
                    this.RaisePropertyChanged("SituacaoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoID {
            get {
                return this.TipoIDField;
            }
            set {
                if ((this.TipoIDField.Equals(value) != true)) {
                    this.TipoIDField = value;
                    this.RaisePropertyChanged("TipoID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteSituacao", Namespace="http://schemas.datacontract.org/2004/07/GestaoClientes.Api.Models")]
    [System.SerializableAttribute()]
    public partial class ClienteSituacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteTipo", Namespace="http://schemas.datacontract.org/2004/07/GestaoClientes.Api.Models")]
    [System.SerializableAttribute()]
    public partial class ClienteTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClientes", ReplyAction="http://tempuri.org/IClienteService/GetClientesResponse")]
        GestaoClientes.Web.ServiceReference1.Cliente[] GetClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClientes", ReplyAction="http://tempuri.org/IClienteService/GetClientesResponse")]
        System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.Cliente[]> GetClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteSituacoes", ReplyAction="http://tempuri.org/IClienteService/GetClienteSituacoesResponse")]
        GestaoClientes.Web.ServiceReference1.ClienteSituacao[] GetClienteSituacoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteSituacoes", ReplyAction="http://tempuri.org/IClienteService/GetClienteSituacoesResponse")]
        System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.ClienteSituacao[]> GetClienteSituacoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteTipos", ReplyAction="http://tempuri.org/IClienteService/GetClienteTiposResponse")]
        GestaoClientes.Web.ServiceReference1.ClienteTipo[] GetClienteTipos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetClienteTipos", ReplyAction="http://tempuri.org/IClienteService/GetClienteTiposResponse")]
        System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.ClienteTipo[]> GetClienteTiposAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CreateCliente", ReplyAction="http://tempuri.org/IClienteService/CreateClienteResponse")]
        void CreateCliente(GestaoClientes.Web.ServiceReference1.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CreateCliente", ReplyAction="http://tempuri.org/IClienteService/CreateClienteResponse")]
        System.Threading.Tasks.Task CreateClienteAsync(GestaoClientes.Web.ServiceReference1.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetCliente", ReplyAction="http://tempuri.org/IClienteService/GetClienteResponse")]
        GestaoClientes.Web.ServiceReference1.Cliente GetCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/GetCliente", ReplyAction="http://tempuri.org/IClienteService/GetClienteResponse")]
        System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.Cliente> GetClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        void UpdateCliente(GestaoClientes.Web.ServiceReference1.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/UpdateCliente", ReplyAction="http://tempuri.org/IClienteService/UpdateClienteResponse")]
        System.Threading.Tasks.Task UpdateClienteAsync(GestaoClientes.Web.ServiceReference1.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DeleteCliente", ReplyAction="http://tempuri.org/IClienteService/DeleteClienteResponse")]
        void DeleteCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/DeleteCliente", ReplyAction="http://tempuri.org/IClienteService/DeleteClienteResponse")]
        System.Threading.Tasks.Task DeleteClienteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : GestaoClientes.Web.ServiceReference1.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<GestaoClientes.Web.ServiceReference1.IClienteService>, GestaoClientes.Web.ServiceReference1.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GestaoClientes.Web.ServiceReference1.Cliente[] GetClientes() {
            return base.Channel.GetClientes();
        }
        
        public System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.Cliente[]> GetClientesAsync() {
            return base.Channel.GetClientesAsync();
        }
        
        public GestaoClientes.Web.ServiceReference1.ClienteSituacao[] GetClienteSituacoes() {
            return base.Channel.GetClienteSituacoes();
        }
        
        public System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.ClienteSituacao[]> GetClienteSituacoesAsync() {
            return base.Channel.GetClienteSituacoesAsync();
        }
        
        public GestaoClientes.Web.ServiceReference1.ClienteTipo[] GetClienteTipos() {
            return base.Channel.GetClienteTipos();
        }
        
        public System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.ClienteTipo[]> GetClienteTiposAsync() {
            return base.Channel.GetClienteTiposAsync();
        }
        
        public void CreateCliente(GestaoClientes.Web.ServiceReference1.Cliente cliente) {
            base.Channel.CreateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task CreateClienteAsync(GestaoClientes.Web.ServiceReference1.Cliente cliente) {
            return base.Channel.CreateClienteAsync(cliente);
        }
        
        public GestaoClientes.Web.ServiceReference1.Cliente GetCliente(int id) {
            return base.Channel.GetCliente(id);
        }
        
        public System.Threading.Tasks.Task<GestaoClientes.Web.ServiceReference1.Cliente> GetClienteAsync(int id) {
            return base.Channel.GetClienteAsync(id);
        }
        
        public void UpdateCliente(GestaoClientes.Web.ServiceReference1.Cliente cliente) {
            base.Channel.UpdateCliente(cliente);
        }
        
        public System.Threading.Tasks.Task UpdateClienteAsync(GestaoClientes.Web.ServiceReference1.Cliente cliente) {
            return base.Channel.UpdateClienteAsync(cliente);
        }
        
        public void DeleteCliente(int id) {
            base.Channel.DeleteCliente(id);
        }
        
        public System.Threading.Tasks.Task DeleteClienteAsync(int id) {
            return base.Channel.DeleteClienteAsync(id);
        }
    }
}
